name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Login to ACR EE instance with token
      uses: aliyun/acr-login@v1
      with:
        region-id: "cn-hangzhou"
        access-key-id: "LTAI4GJLoVRgVKJscWw9ZraM"
        access-key-secret: "lwiofS7v3lPSTQeZ2lhBFSvOaNWTpg"
    - name: Build and push image to ACR EE instance
      run: |
        docker build -t registry.cn-hangzhou.aliyuncs.com/ljing123/repo:github .
        docker push registry.cn-hangzhou.aliyuncs.com/ljing123/repo:github
