name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to ACR EE instance with token
      uses: aliyun/acr-login@v1
      with:
       login-server: "https://registry.cn-hangzhou.aliyuncs.com"
       username: "jing.ljljlj"
       password: "Hello0616"

    - name: Build and push image to ACR  
      run: |
        docker build --tag registry.cn-hangzhou.aliyuncs.com/ljing123/repo:github2 .
        docker push registry.cn-hangzhou.aliyuncs.com/ljing123/repo:github2
        
#     - name: Scan image in ACR
#       uses: aliyun/acr-scan@v1
#       with:
#         region-id: "cn-hangzhou"
#         access-key-id: "LTAI4FfHMnEj829uxy91aaFV"
#         access-key-secret: "96rzqxOoI7RzThJguUg28O4AapHEOf"
#         repository: "registry.cn-hangzhou.aliyuncs.com/ljing123/repo"
#         tag: github2        
    - name: Build and push image to ACR  
    - uses: aliyun/ack-set-context@v1
      with:
        access-key-id: 'LTAI4FfHMnEj829uxy91aaFV'
        access-key-secret: '96rzqxOoI7RzThJguUg28O4AapHEOf'
        cluster-id: 'cf0109eb4648c407dade22da5367d53a6'
