name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to ACR EE instance with token
      uses: aliyun/acr-login@v1
      with:
       login-server:: "https://registry.cn-hangzhou.aliyuncs.com"
       username: "jing.ljljlj"
       password: "Hello0616"

    - name: Build and push image to ACR  
      run: |
        docker build --tag registry.cn-hangzhou.aliyuncs.com/ljing123/repo:github2 .
        docker push registry.cn-hangzhou.aliyuncs.com/ljing123/repo:github2
