name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Login to ACR EE instance with token
      uses: aliyun/acr-login@v1
      with:
        login-server: "https://www-registry.cn-hangzhou.cr.aliyuncs.com"
        region-id: "cn-hangzhou"
        access-key-id: "LTAI4GJLoVRgVKJscWw9ZraM"
        access-key-secret: "lwiofS7v3lPSTQeZ2lhBFSvOaNWTpg"
        instance-id: "cri-skecg851lg5r8brg"
    - name: Build and push image to ACR EE instance
      run: |
        docker build -t www-registry.cn-hangzhou.cr.aliyuncs.com/abc/repo:github .
        docker push www-registry.cn-hangzhou.cr.aliyuncs.com/abc/repo:github
